LICENSE, README.md, rollup.config.js, src/index.test.tsx
=> fix: add rollup babel plugin

rollup.config.js
=> fix: rollup

rollup.config.js
=> fix: make rollup json public

package.json
=> fix: make package public

package-lock.json, package.json
=> fix: attempt semantic release fix

package.json
=> fix: rename package.repository.url

package.json
=> fix: package name

package-lock.json
=> fix: rename package-lock name

.releaserc.js
=> fix: add release-rc

src/index.tsx
=> fix: small change to push release

src/index.tsx
=> fix: small change to push again

src/index.tsx
=> fix: small change to trigger push

.github/workflows/publish_package.yml
=> fix: push again

package-lock.json, package.json
=> fix: try changing package name

.github/workflows/publish_package.yml, package-lock.json, package.json
=> fix: try to get package scopes working

package.json
=> fix: another attempt to fix scope

.github/workflows/publish_package.yml, .github/workflows/pull-requests_check.yml
=> fix: attempt to fix scope

.github/workflows/publish_package.yml
This tries to remove persist-credentials
TESTING=manual
=> fix: attempt scope fix

.github/workflows/publish_package.yml, package.json
=> fix: try to fix scope by changing registry

.github/workflows/publish_package.yml, package-lock.json, package.json
=> fix: change scopes and names back to working version

package.json
=> fix: the push by removing the registry

package.json, rollup.config.js
=> fix: try to rollup code to match other repo

.commitlintrc.json, .releaserc.js
=> fix: change npm release to use dist

package-lock.json, package.json, src/index.test.tsx, src/index.tsx
=> feat: add hoc and expose intersection options

src/index.test.tsx, src/index.tsx
BREAKING CHANGE: this changes the signature on logImpression
TESTING=manual
=> feat: add impression type

src/index.test.tsx, src/index.tsx
also add jsdoc
BREAKING CHANGE: changed the interface to the HOC component.
TESTING=manual
=> clean: rename to logImpressionFunctor

src/index.tsx
=> clean: add comment to trigger deploy

package.json
BREAKING CHANGE: logImpressionFunctor
TESTING=manual
=> feat: increment version

src/index.tsx
=> fix: how changing insertion id works

.commitlintrc.json, src/index.tsx
Delete 'clean' commit type
TESTING=manual
=> chore: push new release

src/index.tsx
It doesn't look like chore causes a push
TESTING=manual
=> fix: trigger a push

src/index.test.tsx, src/index.tsx
BREAKING CHANGE - changes the HOC interface
TESTING=unit tests
=> feat: dict arg, displayname and undefined insertionid

src/index.tsx
BREAKING CHANGE: change the withImpressionTracker HOC
TESTING=manual
=> feat: change hoc's isenabled to take props

src/index.tsx
=> fix: hide no-insertion-id error when disabled

src/index.test.tsx, src/index.tsx
=> fix: how enable==undefined works

src/index.tsx
breaking change
TESTING=unit tests
=> feat: switch to new proto schema

src/index.tsx
BREAKING CHANGE: the last commit switched to using new protos that break the interface
=> feat: force a breaking change for new protos

README.md
BREAKING CHANGE: I think this line needs a colon in it to work correctly.
TESTING=none
=> fix: another PR to force the breaking change

README.md
=> docs: add example to README

src/index.tsx
I learned that a 'refactor' PR does not create a new release.
=> fix: create a PR to push a release

README.md
=> docs: fix docs for local development

package.json, src/index.tsx
=> feat: add impression source type

package-lock.json, src/index.test.tsx, src/index.tsx
fixes PRO-4601
Most clients will use the default (DELIVERY or 1).
TESTING=unit tests
=> feat: support a default ImpressionSourceType; set to DELIVERY

package-lock.json, package.json
I want to debug a possible npm issue by creating another npm version.
TESTING=Ran tests.  I reviewed the code for one of the dependencies.
=> feat: bump dependency versions

src/index.tsx
BREAKING CHANGE: renames logUserId to anonUserId.
TESTING: ran unit tests
=> feat: switch logUserId to anonUserId

README.md
=> docs: remove deprecated `platformName` field

package-lock.json, package.json
Merging more Dependabot PRs.
TESTING=none
=> fix: more deps
